baseURL = "http://paranlee.github.io/"
languageCode = "ko-kr"
title = "Paran Lee's Hugo Site"
theme = "zdoc"

[outputs]
home = ["HTML", "RSS", "JSON"]
enableRobotsTXT = true

[sitemap]
changefreq = "weekly"
filename = "sitemap.xml"
