[[main]]
  identifier = "blog"
  name = "Blog"
  url = "blog"
  weight = 1 

[[main]]
  identifier = "updates"
  name = "Updates"
  url = "updates"
  weight = 2

[[main]]
  identifier = "docs"
  name = "Docs"
  url = "docs"
  weight = 3

# [[main]]
#  identifier = "markdown"
#  name = "Markdown"
#  url = "markdown"
#  weight = 4 
